-- MySQL Script generated by MySQL Workbench
-- Thu May 30 10:35:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdPaint
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdPaint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdPaint` DEFAULT CHARACTER SET utf8 ;
USE `bdPaint` ;

-- -----------------------------------------------------
-- Table `bdPaint`.`colores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdPaint`.`colores` (
  `red` INT NOT NULL,
  `green` INT NOT NULL,
  `blue` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
